### ISSUE TITLE
createChar doesn't work in Firefox

### ISSUE THREAD

**Issue by LunarGem** [LunarGem/fire-and-ice#17]
It doesn't appear that the createCharacter() function is being called from form.submit(). Will have to look into this.

**Comment by Suds-p** [comment]
Ok, think I found what the issue is (didn't work in Chrome either). When debugging, some of the values from the form are a bit unexpected. It gets the values from the input bars just fine, like `name` and `age` and stuff. But from the radio buttons, I just keep getting `"on"`...

I think it's maybe cause the radio buttons have some default value of `"on"`set to them, and you need to update those to "Fire" or "Male" and stuff.

Haven't made a fix for this yet, but I was wondering if you had any code that gets run when createChar.html is loaded, like you do for index.html? If so, you could set the values there...

**Comment by LunarGem** [comment]
Yeah, the createChar() function gets run onsubmit.

**Comment by Suds-p** [comment]
I meant something that runs when the page is loaded, like how `initGame()` works for index.html. With a function like that, you could set up the radio button values in there, and hopefully they'd return the correct values when the form's submitted.

**Comment by Suds-p** [comment]
Oh nvm, found a way less complicated solution. You can set the value of the radio buttons in the markup itself, like this:

```html
<!-- Notice the extra (value="Fire") bit-->

<input type="radio" name="fireice" id="fire" value="Fire"/>  
<label for="fire">Fire</label>
```

Adding those (without changing any of the JS) seems to return the right values from the form. Problem solved :3

**Comment by LunarGem** [comment]
Yay! Just an example of my not remembering how to code HTML...
